### ISSUE TITLE
compile fails- windows 10 - visualstudio -'method_bind_ext.inc': No such file or directory

### ISSUE THREAD

**Issue by blurymind** [sanja-sa/gddragonbones#1]
When trying to compile using the standard procedure under windows, compilation fails at the start with the following error:
```
D:\BUILD\dbonesgodot\godot-2.1.4-stable>scons platform=windows
scons: Reading SConscript files ...
Detected MSVC compiler: amd64
Compiled program architecture will be a 64 bit executable (forcing bits=64).
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] [94mCompiling [95m==> [93mmodules\gddragonbones\gddragonbones.cpp[0m
gddragonbones.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.11.25503\include\xlocale(314): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
modules\gddragonbones\gddragonbones.cpp(8): fatal error C1083: Cannot open include file: 'method_bind_ext.inc': No such file or directory
scons: *** [modules\gddragonbones\gddragonbones.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

**Comment by blurymind** [comment]
could be related to:
https://github.com/godotengine/godot/issues/3260
?

**Comment by sanja-sa** [comment]
I have this file in "godot/core". Try find it there. Maybe it was renamed in new version godot. I can try this problem tomorrow.  20:25, 23 января 2018 г., Todor Imreorov <notifications@github.com>:When trying to compile using the standard procedure under windows, compilation fails at the start with the following error:
D:\BUILD\dbonesgodot\godot-2.1.4-stable>scons platform=windows
scons: Reading SConscript files ...
Detected MSVC compiler: amd64
Compiled program architecture will be a 64 bit executable (forcing bits=64).
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] [94mCompiling [95m==> [93mmodules\gddragonbones\gddragonbones.cpp[0m
gddragonbones.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.11.25503\include\xlocale(314): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
modules\gddragonbones\gddragonbones.cpp(8): fatal error C1083: Cannot open include file: 'method_bind_ext.inc': No such file or directory
scons: *** [modules\gddragonbones\gddragonbones.windows.tools.64.obj] Error 2
scons: building terminated because of errors.


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




Alexander%20V%2E%20Ogurechnikov%20

**Comment by Ranoller** [comment]
I have same error and i find that the file now is "method_bind_ext.gen.inc". I´m compiling right now with include changed. I will report the results.
(file was renamed in 2.1.4 version, i have that in godot 2.1.3.... contents are the same)

**Comment by Ranoller** [comment]
![dragonbonestest1](https://user-images.githubusercontent.com/11712737/35300534-020f2d12-0089-11e8-83e8-b63fa3620983.gif)

Plugin works... i compile without any android flags. In my compiled binary i have this issues changing editor parameters:

·Modulate and bones opacity only works in editor.
.Opacity is fixed to 0-1.
·SelfOpacity do nothing.
·Blend modes doesn´t work.

-Changing GDDragonBones node from parent make this node to lost scale information (looks not changed in editor but in preview isn´t work, you retype that and works another time)
Speed, current animation, loop, progress are ok...


-Exporting are ok, in win7 64 bit (with the mentioned issues).

You are great man!!!.... this can be very funny :) :) :)

Edit: 
Modulate, set_opacity, etc... works from code.
Blend Modes doesn´t work from code.

**Comment by blurymind** [comment]
@Ranoller can you file another issue for the problem you are having.

Thank you ,I will try this now!

**Comment by blurymind** [comment]
I confirm that this fixes the compile bug! Thank you @sanja-sa and @Ranoller  =)
I made a pull request here:
https://github.com/sanja-sa/gddragonbones/pull/2
