### ISSUE TITLE
CanvasItemMaterial doesn´t affect parent DragonBones nodes in Godot 3

### ISSUE THREAD

**Issue by Ranoller** [sanja-sa/gddragonbones#10]
In godot3 behavior is:

CanvasItemMaterial are inherited by child nodes by "child use this material", but parent node (node that have the material), aren´t affeceted by that. If you tick "Use parent material", a dragonbones node can inherit from a grandparent node if the parent is other dragonbones node that have ticked "child use this material", but without a parent with this option, dragonbones node aren´t using any material.

In godot 2 dragon bones node behavior is:

Tick child use this material ---> activates material in current node
Tick use parent ---> inherit parent material

All tested i godot 2 y 3 compiled at 01/02/2018 and dragon bones module in last commit at same day.

**Comment by sanja-sa** [comment]
@Ranoller 
How it work for me in Godot 3:

1. **checked** _'Use Parent Material'_, **checked** _'Childs Use This Material'_ -- material for all DB nodes will be as **ANY** parent  material. Right?

2. **unchecked** _'Use Parent Material'_, **checked** _'Childs Use This Material'_ -- material for all DB nodes will be as root of DB (Node where select resource DB file). Right?

3. **unchecked** _'Use Parent Material'_, **unchecked** _'Childs Use This Material'_ -- material for all DB nodes will as themself (in Godot 3 used for Add, Sub, Mul CanvasItemMaterial setuped in DB editor, in Godot 2 not using). Right?

4. **checked** _'Use Parent Material'_, **unchecked** _'Childs Use This Material'_ -- same as 3. Right? Because, childs use themself materials (priority).

How it should work, by your opinion?

**Comment by Ranoller** [comment]
Ok, I think that i missunderstanding the behavior. Playing with that i can do any configuration. My missunderstanding was the word "child" in the node, with tick use parent material you inherited parent, but if you don´t tick childs use this material, material is not  applied... childs are the internal nodes of the dragonbones node. Understanding that the behavior is clear. Thanks!
