### ISSUE TITLE
dragonbones 4_5 file format -strange rotation on jaw when altering progress value in editor

### ISSUE THREAD

**Issue by blurymind** [sanja-sa/gddragonbones#6]
Using this test file, provided by @Ranoller:
[DragonBonesExport4_5.zip](https://github.com/sanja-sa/gddragonbones/files/1668969/DragonBonesExport4_5.zip)

Changing the progress value, results in a strange pose of the jaw bone:
![capture](https://user-images.githubusercontent.com/6495061/35457344-7f5e9de0-02d0-11e8-80e9-3ca0a7fc85c7.JPG)

Note that this is a minor issue, as it doesnt affect the game during runtime

It looks like it is flipping on Y the slot

**Comment by Ranoller** [comment]
Probably this is not a bug... I explain myself in the upper issue.

**Comment by blurymind** [comment]
It seems to also do it on a 4_5 file I exported from dragonbones 4.9.5

It only affects the editor, while the animation is not playing - so its not really serious. Just worth noting

**Comment by sanja-sa** [comment]
I think this is a bug. This happens, when mesh or texture havn't any bones for FFD, I'll testing it on next week more seriosly.

**Comment by Ranoller** [comment]
If it will be investigated i say that thing that happend with the dragon model is that several bones are flipped verticaly in rest position. I try to investigate the json exports but i didn't found nothing suspicious because the differences between formats (so many scalated numbers). In dragonbones editor i didn't find nothing, no bones flipped...i suspice in dragon bones spine importer leaving some kind of not expected data in dragonbones json exports

**Comment by Ranoller** [comment]
Take in count the "no loop" problem of this model (that not happend in the demon cocos imported)

**Comment by sanja-sa** [comment]
Try this https://github.com/sanja-sa/gddragonbones/commit/8edc00281c54df68594f53357171cd54b75cac49

**Comment by blurymind** [comment]
@sanja-sa fantastic commits!! This fixes it. Closing this now
